# Generated by Django 6.1.1 on 2026-09-24 15:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('pilots', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimator_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('is_provisional', models.BooleanField(default=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('confidence_threshold', models.FloatField(default=0.4)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseline_version', models.CharField(db_index=True, max_length=100)),
                ('resting_heart_rate', models.FloatField()),
                ('baseline_rmssd', models.FloatField(blank=True, null=True)),
                ('baseline_sdnn', models.FloatField(blank=True, null=True)),
                ('baseline_mean_rr', models.FloatField(blank=True, null=True)),
                ('calibration_duration_sec', models.FloatField(blank=True, null=True)),
                ('is_calibrated', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='pilots.pilot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('fatigue_state', models.CharField(choices=[('NORMAL', 'Normal'), ('ELEVATED_WORKLOAD', 'Elevated Workload'), ('FATIGUE', 'Fatigue'), ('INSUFFICIENT_DATA', 'Insufficient Data')], db_index=True, max_length=50)),
                ('fatigue_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('overall_sqi', models.FloatField(default=1.0)),
                ('dominant_factors', models.JSONField(blank=True, default=list)),
                ('estimator_id', models.CharField(default='ProvisionalRuleBasedEstimator', max_length=100)),
                ('is_provisional', models.BooleanField(default=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('confidence_threshold_used', models.FloatField(default=0.4)),
                ('baseline_version_used', models.CharField(blank=True, max_length=100, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_estimates', to='telemetry.featurewindow')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_estimates', to='missions.mission')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_estimates', to='pilots.pilot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
