# Generated by Django 6.1.1 on 2026-09-21 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('pilots', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('baseline_value', models.FloatField()),
                ('std_deviation', models.FloatField(blank=True, null=True)),
                ('sample_count', models.IntegerField()),
                ('window_duration', models.IntegerField()),
                ('calculated_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('baseline_version', models.CharField(max_length=100)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='pilots.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='StateEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('fatigue_score', models.FloatField()),
                ('workload_score', models.FloatField()),
                ('stress_score', models.FloatField()),
                ('recovery_score', models.FloatField()),
                ('overall_risk_score', models.FloatField()),
                ('fatigue_state', models.CharField(max_length=50)),
                ('overall_state', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('explanation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_estimates', to='telemetry.featurewindow')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_estimates', to='missions.mission')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_estimates', to='intelligence.modelversion')),
            ],
        ),
    ]
