# Generated by Django 6.1.1 on 2026-09-21 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('window_duration', models.IntegerField()),
                ('sample_count', models.IntegerField()),
                ('signal_quality', models.FloatField()),
                ('feature_status', models.CharField(choices=[('VALID', 'Valid'), ('PARTIAL', 'Partial'), ('INVALID', 'Invalid')], max_length=20)),
                ('mean_hr', models.FloatField(blank=True, null=True)),
                ('hr_std', models.FloatField(blank=True, null=True)),
                ('mean_rr', models.FloatField(blank=True, null=True)),
                ('rmssd', models.FloatField(blank=True, null=True)),
                ('sdnn', models.FloatField(blank=True, null=True)),
                ('activity_mean', models.FloatField(blank=True, null=True)),
                ('spo2_mean', models.FloatField(blank=True, null=True)),
                ('skin_temp_mean', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_windows', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='SignalQuality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('signal_type', models.CharField(max_length=100)),
                ('quality_score', models.FloatField()),
                ('quality_status', models.CharField(choices=[('GOOD', 'Good'), ('ACCEPTABLE', 'Acceptable'), ('POOR', 'Poor'), ('INVALID', 'Invalid')], max_length=20)),
                ('artifact_ratio', models.FloatField(blank=True, null=True)),
                ('missing_ratio', models.FloatField(blank=True, null=True)),
                ('noise_detected', models.BooleanField(default=False)),
                ('quality_flags', models.JSONField(default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_quality', to='devices.device')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_quality', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('rr_interval', models.FloatField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('skin_temperature', models.FloatField(blank=True, null=True)),
                ('activity_level', models.FloatField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='missions.mission')),
            ],
        ),
    ]
