# Generated by Django 6.1.1 on 2026-09-24 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('missions', '0001_initial'),
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('window_duration_sec', models.FloatField()),
                ('mean_hr', models.FloatField(blank=True, null=True)),
                ('min_hr', models.FloatField(blank=True, null=True)),
                ('max_hr', models.FloatField(blank=True, null=True)),
                ('hr_std', models.FloatField(blank=True, null=True)),
                ('mean_rr_ms', models.FloatField(blank=True, null=True)),
                ('sdnn_ms', models.FloatField(blank=True, null=True)),
                ('rmssd_ms', models.FloatField(blank=True, null=True)),
                ('pnn50_percent', models.FloatField(blank=True, null=True)),
                ('mean_magnitude', models.FloatField(blank=True, null=True)),
                ('activity_intensity', models.FloatField(blank=True, null=True)),
                ('baseline_available', models.BooleanField(default=False)),
                ('hr_deviation_from_baseline', models.FloatField(blank=True, null=True)),
                ('hrv_rmssd_ratio_to_baseline', models.FloatField(blank=True, null=True)),
                ('features_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_windows', to='devices.device')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_windows', to='missions.mission')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_windows', to='pilots.pilot')),
            ],
            options={
                'ordering': ['-window_end'],
            },
        ),
        migrations.CreateModel(
            name='SignalQuality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('overall_sqi', models.FloatField()),
                ('is_telemetry_acceptable', models.BooleanField(default=True)),
                ('motion_corruption_index', models.FloatField(default=0.0)),
                ('channels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_qualities', to='devices.device')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_qualities', to='missions.mission')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_qualities', to='pilots.pilot')),
            ],
            options={
                'verbose_name_plural': 'Signal Qualities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('rr_interval', models.JSONField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('skin_temperature', models.FloatField(blank=True, null=True)),
                ('activity_level', models.JSONField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='missions.mission')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='pilots.pilot')),
            ],
            options={
                'verbose_name_plural': 'Telemetry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
